# Generated by Django 5.1.3 on 2024-11-07 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_permissionrequest_additional_date_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequestAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('position', models.CharField(max_length=50, verbose_name='Cargo')),
                ('establishment', models.CharField(max_length=100, verbose_name='Establecimiento')),
                ('solicita_permiso_administrativo', models.BooleanField(default=False, verbose_name='Solicita permiso administrativo')),
                ('con_goce_remuneracion', models.BooleanField(default=False, verbose_name='Con goce de remuneración')),
                ('sin_goce_remuneracion', models.BooleanField(default=False, verbose_name='Sin goce de remuneración')),
                ('number_of_days', models.PositiveIntegerField(verbose_name='Número de días')),
                ('date_from', models.DateField(verbose_name='Fecha desde')),
                ('date_to', models.DateField(verbose_name='Fecha hasta')),
                ('jornada', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=10, verbose_name='Jornada')),
                ('solicita_compensacion', models.BooleanField(default=False, verbose_name='Solicita compensación de tiempo')),
                ('number_of_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de horas')),
                ('comp_date_from', models.DateField(blank=True, null=True, verbose_name='Fecha desde (compensación)')),
                ('comp_date_to', models.DateField(blank=True, null=True, verbose_name='Fecha hasta (compensación)')),
                ('comp_time_from', models.TimeField(blank=True, null=True, verbose_name='Horario desde')),
                ('comp_time_to', models.TimeField(blank=True, null=True, verbose_name='Horario hasta')),
                ('firma_funcionario', models.FileField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma del funcionario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
