# Generated by Django 5.1.3 on 2024-11-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_remove_permissionrequestadmin_con_goce_remuneracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='jornada',
            field=models.CharField(choices=[('Completa', 'Completa'), ('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=50),
        ),
    ]
