# Generated by Django 5.1.3 on 2024-11-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0006_alter_permissionrequestadmin_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='jornada',
            field=models.CharField(choices=[('Completa', 'Completa'), ('Mañana', 'Mañana'), ('Tarde', 'Tarde')], default='Completa', max_length=50),
        ),
    ]
