# Generated by Django 5.1.3 on 2024-11-11 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0007_alter_permissionrequestadmin_jornada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='permissionrequestadmin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='date_from',
            field=models.DateField(verbose_name='Fecha desde'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='date_to',
            field=models.DateField(verbose_name='Fecha hasta'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='establishment',
            field=models.CharField(max_length=100, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='firma_funcionario',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma del funcionario'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='jornada',
            field=models.CharField(choices=[('Completa', 'Completa'), ('Mañana', 'Mañana'), ('Tarde', 'Tarde')], default='Completa', max_length=50, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='number_of_days',
            field=models.PositiveIntegerField(verbose_name='Número de días'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='RUT'),
        ),
    ]
