# Generated by Django 5.1.3 on 2024-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('request_type', models.CharField(choices=[('FERIADO', 'Solicitud de Feriado Legal'), ('ADMINISTRATIVO', 'Permiso Administrativo'), ('COMPENSACION', 'Compensación de Tiempo')], max_length=20)),
            ],
        ),
    ]
