# Generated by Django 5.1.3 on 2024-11-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0010_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='establishment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Permisos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo'),
        ),
    ]
