# Generated by Django 5.1.3 on 2024-11-13 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0014_remove_permissionrequest_holiday_requested_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequestadmin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
