# Generated by Django 5.1.3 on 2024-11-13 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0015_permissionrequestadmin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='request_type',
            field=models.CharField(choices=[('FERIADO', 'Solicitud de Feriado Legal'), ('ADMINISTRATIVO', 'Permiso Administrativo'), ('COMPENSACION', 'Compensación de Tiempo')], default='FERIADO', max_length=20, verbose_name='Tipo de Solicitud'),
        ),
        migrations.AlterField(
            model_name='compensationrequest',
            name='establishment',
            field=models.CharField(choices=[('Posta de Salud Rural Villa Baviera', 'Posta de Salud Rural Villa Baviera'), ('Posta de Salud Rural Los Canelos', 'Posta de Salud Rural Los Canelos'), ('Posta de Salud Rural Bullileo', 'Posta de Salud Rural Bullileo'), ('Posta de Salud Rural Bajos de Huenutil', 'Posta de Salud Rural Bajos de Huenutil'), ('Posta de Salud Rural Catillo', 'Posta de Salud Rural Catillo'), ('Posta de Salud Rural Digua', 'Posta de Salud Rural Digua'), ('Posta de Salud Rural Monte Flor', 'Posta de Salud Rural Monte Flor'), ('Posta de Salud Rural San Alejo', 'Posta de Salud Rural San Alejo'), ('Posta de Salud Rural Talquita', 'Posta de Salud Rural Talquita'), ('Posta de Salud Rural Los Carros', 'Posta de Salud Rural Los Carros'), ('Posta de Salud Rural Perquilauquén', 'Posta de Salud Rural Perquilauquén'), ('Posta de Salud Rural La Orilla', 'Posta de Salud Rural La Orilla'), ('Posta de Salud Rural Fuerte Viejo', 'Posta de Salud Rural Fuerte Viejo'), ('Centro Comunitario de Salud Familiar Los Olivos', 'Centro Comunitario de Salud Familiar Los Olivos'), ('Centro de Salud Familiar Arrau Méndez', 'Centro de Salud Familiar Arrau Méndez'), ('SAR', 'SAR'), ('Hospital San José', 'Hospital San José'), ('Centro Comunitario de Salud Familiar Buenos Aires', 'Centro Comunitario de Salud Familiar Buenos Aires'), ('Departamento de Salud Municipal Parral', 'Departamento de Salud Municipal Parral')], max_length=100, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='permission',
            name='request_type',
            field=models.CharField(choices=[('FERIADO', 'Solicitud de Feriado Legal'), ('ADMINISTRATIVO', 'Permiso Administrativo'), ('COMPENSACION', 'Compensación de Tiempo')], default='FERIADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='establishment',
            field=models.CharField(choices=[('Posta de Salud Rural Villa Baviera', 'Posta de Salud Rural Villa Baviera'), ('Posta de Salud Rural Los Canelos', 'Posta de Salud Rural Los Canelos'), ('Posta de Salud Rural Bullileo', 'Posta de Salud Rural Bullileo'), ('Posta de Salud Rural Bajos de Huenutil', 'Posta de Salud Rural Bajos de Huenutil'), ('Posta de Salud Rural Catillo', 'Posta de Salud Rural Catillo'), ('Posta de Salud Rural Digua', 'Posta de Salud Rural Digua'), ('Posta de Salud Rural Monte Flor', 'Posta de Salud Rural Monte Flor'), ('Posta de Salud Rural San Alejo', 'Posta de Salud Rural San Alejo'), ('Posta de Salud Rural Talquita', 'Posta de Salud Rural Talquita'), ('Posta de Salud Rural Los Carros', 'Posta de Salud Rural Los Carros'), ('Posta de Salud Rural Perquilauquén', 'Posta de Salud Rural Perquilauquén'), ('Posta de Salud Rural La Orilla', 'Posta de Salud Rural La Orilla'), ('Posta de Salud Rural Fuerte Viejo', 'Posta de Salud Rural Fuerte Viejo'), ('Centro Comunitario de Salud Familiar Los Olivos', 'Centro Comunitario de Salud Familiar Los Olivos'), ('Centro de Salud Familiar Arrau Méndez', 'Centro de Salud Familiar Arrau Méndez'), ('SAR', 'SAR'), ('Hospital San José', 'Hospital San José'), ('Centro Comunitario de Salud Familiar Buenos Aires', 'Centro Comunitario de Salud Familiar Buenos Aires'), ('Departamento de Salud Municipal Parral', 'Departamento de Salud Municipal Parral')], max_length=50, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='establishment',
            field=models.CharField(choices=[('Posta de Salud Rural Villa Baviera', 'Posta de Salud Rural Villa Baviera'), ('Posta de Salud Rural Los Canelos', 'Posta de Salud Rural Los Canelos'), ('Posta de Salud Rural Bullileo', 'Posta de Salud Rural Bullileo'), ('Posta de Salud Rural Bajos de Huenutil', 'Posta de Salud Rural Bajos de Huenutil'), ('Posta de Salud Rural Catillo', 'Posta de Salud Rural Catillo'), ('Posta de Salud Rural Digua', 'Posta de Salud Rural Digua'), ('Posta de Salud Rural Monte Flor', 'Posta de Salud Rural Monte Flor'), ('Posta de Salud Rural San Alejo', 'Posta de Salud Rural San Alejo'), ('Posta de Salud Rural Talquita', 'Posta de Salud Rural Talquita'), ('Posta de Salud Rural Los Carros', 'Posta de Salud Rural Los Carros'), ('Posta de Salud Rural Perquilauquén', 'Posta de Salud Rural Perquilauquén'), ('Posta de Salud Rural La Orilla', 'Posta de Salud Rural La Orilla'), ('Posta de Salud Rural Fuerte Viejo', 'Posta de Salud Rural Fuerte Viejo'), ('Centro Comunitario de Salud Familiar Los Olivos', 'Centro Comunitario de Salud Familiar Los Olivos'), ('Centro de Salud Familiar Arrau Méndez', 'Centro de Salud Familiar Arrau Méndez'), ('SAR', 'SAR'), ('Hospital San José', 'Hospital San José'), ('Centro Comunitario de Salud Familiar Buenos Aires', 'Centro Comunitario de Salud Familiar Buenos Aires'), ('Departamento de Salud Municipal Parral', 'Departamento de Salud Municipal Parral')], max_length=100, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='establishment',
            field=models.CharField(blank=True, choices=[('Posta de Salud Rural Villa Baviera', 'Posta de Salud Rural Villa Baviera'), ('Posta de Salud Rural Los Canelos', 'Posta de Salud Rural Los Canelos'), ('Posta de Salud Rural Bullileo', 'Posta de Salud Rural Bullileo'), ('Posta de Salud Rural Bajos de Huenutil', 'Posta de Salud Rural Bajos de Huenutil'), ('Posta de Salud Rural Catillo', 'Posta de Salud Rural Catillo'), ('Posta de Salud Rural Digua', 'Posta de Salud Rural Digua'), ('Posta de Salud Rural Monte Flor', 'Posta de Salud Rural Monte Flor'), ('Posta de Salud Rural San Alejo', 'Posta de Salud Rural San Alejo'), ('Posta de Salud Rural Talquita', 'Posta de Salud Rural Talquita'), ('Posta de Salud Rural Los Carros', 'Posta de Salud Rural Los Carros'), ('Posta de Salud Rural Perquilauquén', 'Posta de Salud Rural Perquilauquén'), ('Posta de Salud Rural La Orilla', 'Posta de Salud Rural La Orilla'), ('Posta de Salud Rural Fuerte Viejo', 'Posta de Salud Rural Fuerte Viejo'), ('Centro Comunitario de Salud Familiar Los Olivos', 'Centro Comunitario de Salud Familiar Los Olivos'), ('Centro de Salud Familiar Arrau Méndez', 'Centro de Salud Familiar Arrau Méndez'), ('SAR', 'SAR'), ('Hospital San José', 'Hospital San José'), ('Centro Comunitario de Salud Familiar Buenos Aires', 'Centro Comunitario de Salud Familiar Buenos Aires'), ('Departamento de Salud Municipal Parral', 'Departamento de Salud Municipal Parral')], max_length=100, null=True, verbose_name='Establecimiento'),
        ),
    ]
