# Generated by Django 5.1.3 on 2024-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0017_alter_permission_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='permissionrequestadmin',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='request_type',
            field=models.CharField(choices=[('FERIADO', 'Solicitud de Feriado Legal'), ('ADMINISTRATIVO', 'Permiso Administrativo'), ('COMPENSACION', 'Compensación de Tiempo')], default='FERIADO', max_length=20, verbose_name='Tipo de Solicitud'),
        ),
    ]
