# Generated by Django 5.1.3 on 2024-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0018_compensationrequest_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AlterField(
            model_name='compensationrequest',
            name='establishment',
            field=models.CharField(choices=[('Posta de Salud Rural Villa Baviera', 'Posta de Salud Rural Villa Baviera')], max_length=100, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='compensationrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No Autorizado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='compensationrequest',
            name='position',
            field=models.CharField(choices=[('Dentista', 'Dentista'), ('Medico', 'Médico')], max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='additional_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha adicional desde'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='additional_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha adicional hasta'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='establishment',
            field=models.CharField(choices=[('Posta de Salud Rural Villa Baviera', 'Posta de Salud Rural Villa Baviera')], max_length=50, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No Autorizado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='position',
            field=models.CharField(choices=[('Dentista', 'Dentista'), ('Medico', 'Médico')], max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='establishment',
            field=models.CharField(choices=[('Posta de Salud Rural Villa Baviera', 'Posta de Salud Rural Villa Baviera')], max_length=100, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No Autorizado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='position',
            field=models.CharField(choices=[('Dentista', 'Dentista'), ('Medico', 'Médico')], max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='establishment',
            field=models.CharField(blank=True, choices=[('Posta de Salud Rural Villa Baviera', 'Posta de Salud Rural Villa Baviera')], max_length=100, null=True, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('Dentista', 'Dentista'), ('Medico', 'Médico')], max_length=50, null=True, verbose_name='Cargo'),
        ),
    ]
