# Generated by Django 5.1.3 on 2024-11-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0020_alter_compensationrequest_establishment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('request_type', models.CharField(choices=[('feriado', 'Solicitud de Feriado Legal'), ('administrativo', 'Permiso Administrativo'), ('compensacion', 'Compensación de Tiempo')], default='FERIADO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='compensationrequest',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='permissionrequestadmin',
            name='estado',
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='additional_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha desde'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='additional_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha hasta'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=10),
        ),
    ]
