# Generated by Django 5.1.3 on 2024-11-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0021_permission_remove_compensationrequest_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='permissionrequestadmin',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=10),
        ),
    ]
