# Generated by Django 5.1.3 on 2024-11-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0023_permissionrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No Autorizado'), ('completado', 'Completado')], default='pendiente', max_length=13, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No Autorizado'), ('completado', 'Completado')], default='pendiente', max_length=13, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No Autorizado'), ('completado', 'Completado')], default='pendiente', max_length=13, verbose_name='Estado'),
        ),
    ]
