# Generated by Django 5.1.3 on 2024-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0024_alter_compensationrequest_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No Autorizado'), ('completado', 'Completado')], default='pendiente', max_length=15),
        ),
    ]
