# Generated by Django 5.1.3 on 2024-12-09 17:59

import permisos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0026_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationrequest',
            name='rut',
            field=models.CharField(max_length=12, validators=[permisos.models.validate_rut], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='rut',
            field=models.CharField(max_length=12, validators=[permisos.models.validate_rut], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='rut',
            field=models.CharField(max_length=12, validators=[permisos.models.validate_rut], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='permissionrequestadmin',
            name='rut',
            field=models.CharField(max_length=12, validators=[permisos.models.validate_rut], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(max_length=12, validators=[permisos.models.validate_rut], verbose_name='RUT'),
        ),
    ]
