# Generated by Django 5.1.3 on 2024-12-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0027_alter_compensationrequest_rut_alter_permission_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='approver_signature',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_aprobadores/', verbose_name='Firma del aprobador'),
        ),
    ]
