# Generated by Django 5.1.3 on 2025-01-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0028_permissionrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('usuario_normal', 'Usuario Normal'), ('admin', 'Administrador')], default='usuario_normal', max_length=50, verbose_name='Tipo de Usuario'),
        ),
    ]
